language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-head
jdk:
  - openjdk7
env:
  - JRUBY_OPTS='-X+O -J-Djruby.launch.inproc=false'
gemfile: server/Gemfile
install:
  - cd server
  - bundle install
script:
  - bundle exec rake test
notifications:
  email:
    - mi@mifo.sk
    - marios@redhat.com
    - lutter@redhat.com
    - rlandy@redhat.com
  irc:
    channels:
      - "irc.freenode.org#deltacloud"
    use_notice: true
    skip_join: false

