language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-19mode
gemfile: server/Gemfile
install:
  - cd server
  - bundle install
script:
  - bundle exec rake test
notifications:
  email:
    - mi@mifo.sk
  irc:
    channels:
      - "irc.freenode.org#deltacloud"
    use_notice: true
    skip_join: false
