---
:arubacloud:
  :entrypoints:
    compute:
      dc1: https://api.dc1.computing.cloud.it/WsEndUser/v2.4/WsEndUser.svc?wsdl
      dc2: https://api.dc2.computing.cloud.it/WsEndUser/v2.4/WsEndUser.svc?wsdl
      dc3: https://api.dc3.computing.cloud.it/WsEndUser/v2.4/WsEndUser.svc?wsdl
      dc4: https://api.dc4.computing.cloud.it/WsEndUser/v2.4/WsEndUser.svc?wsdl
  :name: Arubacloud
