---
:ec2:
  :entrypoints:
    s3:
      us-west-1: s3-us-west-1.amazonaws.com
      us-west-2: s3-us-west-2.amazonaws.com
      ap-southeast-1: s3-ap-southeast-1.amazonaws.com
      ap-northeast-1: s3-ap-northeast-1.amazonaws.com
      eu-west-1: s3-eu-west-1.amazonaws.com
      us-east-1: s3.amazonaws.com
      sa-east-1: s3-sa-east-1.amazonaws.com
    elb:
      us-west-1: elasticloadbalancing.us-west-1.amazonaws.com
      us-west-2: elasticloadbalancing.us-west-2.amazonaws.com
      ap-southeast-1: elasticloadbalancing.ap-southeast-1.amazonaws.com
      ap-northeast-1: elasticloadbalancing.ap-northeast-1.amazonaws.com
      eu-west-1: elasticloadbalancing.eu-west-1.amazonaws.com
      us-east-1: elasticloadbalancing.us-east-1.amazonaws.com
      sa-east-1: elasticloadbalancing.sa-east-1.amazonaws.com
    ec2:
      us-west-1: ec2.us-west-1.amazonaws.com
      us-west-2: ec2.us-west-2.amazonaws.com
      ap-southeast-1: ec2.ap-southeast-1.amazonaws.com
      ap-northeast-1: ec2.ap-northeast-1.amazonaws.com
      eu-west-1: ec2.eu-west-1.amazonaws.com
      us-east-1: ec2.us-east-1.amazonaws.com
      sa-east-1: ec2.sa-east-1.amazonaws.com
    mon:
      us-west-1: monitoring.us-west-1.amazonaws.com
      us-west-2: monitoring.us-west-2.amazonaws.com
      ap-southeast-1: monitoring.ap-southeast-1.amazonaws.com
      ap-northeast-1: monitoring.ap-northeast-1.amazonaws.com
      eu-west-1: monitoring.eu-west-1.amazonaws.com
      us-east-1: monitoring.us-east-1.amazonaws.com
      sa-east-1: monitoring.sa-east-1.amazonaws.com
  :name: EC2
